CoffeeShop/Controllers/MealController.cs
using CoffeeShop.Config;
using CoffeeShop.DataDTO;
using CoffeeShop.Models;
using CoffeeShop.Models.IServices;
using CoffeeShop.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Web.WebPages;

namespace CoffeeShop.Controllers
{

    
    public class MealController : Controller
    {
            

        private IMealService _mealService;
        private readonly IHttpContextAccessor _httpContextAssessor;

        public MealController(IMealService mealService, IHttpContextAccessor httpContextAccessor)
        {
                _mealService = mealService;
            _httpContextAssessor = httpContextAccessor;     
           
            
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            
            try
            {
                var result = await _mealService.GetAllMeal();
                return View(result);
            }
            catch(Exception ex)
            {
                return BadRequest(ex.Message);  
            }

           
        }

        //public IActionResult CreateMeal() => View(new CreateFoodDTO());

        public IActionResult CreateMeal()
        {
            var Access_Token = Request.Cookies["Access_Token"];
            ViewBag.Access_Token = Access_Token; // Pass the JWT token to the view

            return View();
        }

        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "Customer")]
        [HttpPost]
        [Route("Meal/CreateMeal")]
       
        public async Task<IActionResult> CreateMeal(CreateFoodDTO foodDto)
        {

                 

            if (!ModelState.IsValid)
            {
                return View(foodDto);
            }


            try
            {
                if (foodDto != null)
                {

                    var result = await _mealService.MealCreate(foodDto);
                    if (result == "successfully create meal")
                    {
                        return View("MealReturnResult");
                    }

                }
                return View("MealReturnResult");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        
        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            try
            {
                var result = await _mealService.Details(id);
                return View(result);
            }
            catch(Exception ex)
            {
                return BadRequest(ex.Message);
            }
              
        }
    }
}

CoffeeShop/Controllers/MyColdDrinkController.cs
using CoffeeShop.Models.IServices;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShop.Controllers
{
    public class MyColdDrinkController : Controller
    {
        private readonly IColdDrinkService _coldDrinkService;

        public MyColdDrinkController(IColdDrinkService coldDrinkService)
        {
                _coldDrinkService = coldDrinkService;   
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                var result = await _coldDrinkService.GetColdDrink();
                return View(result); ;
            }
            catch (Exception ex) 
            {
                return BadRequest(ex.Message);  
            }
           
        }
    }
}

CoffeeShop/Controllers/MyHotDrinkController.cs
using CoffeeShop.Models.IServices;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShop.Controllers
{
    public class MyHotDrinkController : Controller
    {
        private readonly IHotDrinkService _hotDrinkService;

        public MyHotDrinkController(IHotDrinkService hotDrinkService)
        {
                _hotDrinkService = hotDrinkService; 
        }
        public async Task<IActionResult> Index()
        {
            try
            {
               var result = await _hotDrinkService.GetHotDrink();
                return View(result);
            }
            catch (Exception ex)
            { 
                return BadRequest(ex.Message);  
            }
           
        }
    }
}

CoffeeShop/Views/Shared/CreateMealss.cshtml
<a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Meal" asp-action="CreateMeal">
    <i class="bi bi-person-plus"></i> CreateMeals
</a>

CoffeeShop/Views/Shared/Identity.cshtml
@using Microsoft.AspNetCore.Identity

@inject UserManager<AppUser> UserManager; 

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="LogIn">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}

else
{

  @*User profile section*@

    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="MyUser">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

CoffeeShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoffeeShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoffeeShop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoffeeShop</a>
                <a class="navbar-brand" asp-area="" asp-controller="Meal" asp-action="Index">Food</a>
                <a class="navbar-brand" asp-area="" asp-controller="MyColdDrink" asp-action="Index">ColdDrink</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Meal" asp-action="Index"><i class="bi bi-film"></i> Food</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyColdDrink" asp-action="Index"><i class="bi bi-film"></i>ColdDrink</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyHotDrink" asp-action="Index"><i class="bi bi-film"></i>HotDrink</a>
                        </li>


                        </li>
                    </ul>
                    <partial name="identity.cshtml" />
                    <partial name="CreateMealss.cshtml" />
                </div>
            </div>
        </nav>
       
    </header>
   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
       
        <div class="container">
            &copy; 2023 - CoffeeShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>